### ISSUE TITLE
ManagementClient.GetContentTypes will only return the first 100 content types

### ISSUE THREAD

**Issue by geoffhardy1** [contentful/contentful.net#181] opened 2019-04-25 20:48 UTC
When we call the GetContentTypes method on ManagementClient, we only get back the first 100 content types. There does not seem to be a way to increase this limit so that we can get them all back.

**Comment by geoffhardy1** [comment] 2019-04-25 21:18
One simple option for fixing this is to add ?limit=1000 to the query in the GetContentTypes method.

**Comment by Roblinde** [comment] 2019-10-24 06:29
This is by design in the underlying API. To retrieve them all you would need to increase the limit (as suggested above) or paginate the response using `skip` and `limit.`

**Comment by geoffhardy1** [comment] 2019-10-25 22:42
The problem is that there is no way to do this using the GetContentTypes method, since it only ever lets you get the first 100.

It is not possible to use this method to get content type 101 onwards.
________________________________

**Comment by Roblinde** [comment] 2019-10-26 09:25
Ah, you are right. It doesn't allow for a querystring to be passed. I'll get that fixed in the next version,

**Comment by Roblinde** [comment] 2019-11-01 14:08
@geoffhardy1  thanks for reporting this, it should now be possible to pass a querystring to the call in version 4.3.0.

**Closed by Roblinde** 2019-11-01 14:08 UTC
