### ISSUE TITLE
Embedded inline reference not being mapped

### ISSUE THREAD

**Issue by sam-c-dfe** [contentful/contentful.net#352] opened 2024-10-08 08:25 UTC
**Affected versions:** 8.1 & 8.2

**Issue:**
We have a scenario where we have an entry field that consists of multiple references that each contain a rich text field that has an embedded inline entry reference that points to the same entry. In version 8.0.1 these were getting mapped correctly however after recently upgrading to 8.2 these are no longer being mapped. The Target is null except for the first entry that references it.
The issue looks to be a repeat of this: [https://github.com/contentful/contentful.net/issues/333](https://github.com/contentful/contentful.net/issues/333).

**Structure**
Main entry
-Multi-reference field
--reference entry A
---sub ref A (inline entry in richtext field)
--reference entry B
---sub ref A (inline entry in richtext field)
--reference entry C
---sub ref A (inline entry in richtext field)

**Workaround:** Downgrade to 8.0.1

**Comment by Roblinde** [comment] 2024-10-08 14:08
@sam-c-dfe thanks for this. I'll have a look. Do you have a redacted sample request? Would make it easier to write a unit test and reproduce the problem.

**Comment by sam-c-dfe** [comment] 2024-10-10 12:26
@Roblinde Hello, please see a cut down version of the data we get from the query: 
[response.json](https://github.com/user-attachments/files/17328032/response.json)

Hope this helps

**Comment by Roblinde** [comment] 2024-10-10 16:09
Perfect, thank you. I'll look into it !

**Comment by Roblinde** [comment] 2024-10-10 18:18
This has been an elusive problem for some time. With an example json I could reproduce and find the cause. This should now be resolved in version 8.3.0

Thanks!

**Closed by Roblinde** 2024-10-10 18:18 UTC
